"""
Configuration file for the PDF Q&A System
Auto-generated by model_selector.py
"""

# QA Engine Configuration
QA_CONFIG = {
    # Mode: 'extractive' (fast, accurate, uses regex) or 'generative' (slower, uses AI)
    'mode': 'extractive' if 'extractive' == 'extractive' else 'advanced',

    # Use advanced QA model (requires more memory but better accuracy)
    'use_advanced_qa': False,

    # Advanced QA model to use if use_advanced_qa=True
    'advanced_qa_model': 'extractive',

    # Use full document context instead of just top chunks (better accuracy)
    'use_full_context': True,

    # Number of top chunks to retrieve (only used if use_full_context=False)
    'top_k_chunks': 10,

    # Maximum answer length
    'max_answer_length': 3000,
}

# Embedding Model Configuration
EMBEDDING_CONFIG = {
    # Using reliable model that works well
    'model_name': 'all-MiniLM-L6-v2',
}

# Reranker Configuration (disabled for speed)
RERANKER_CONFIG = {
    'enabled': False,
    'model_name': 'cross-encoder/ms-marco-MiniLM-L-6-v2',
    'top_k': 5,
}

# Retrieval Configuration
RETRIEVAL_CONFIG = {
    # Number of chunks for specific questions (lower for speed)
    'initial_k': 3,
    # Number of chunks for summary questions (higher for context)
    'summary_k': 15,
    # Use MMR for summaries to get diverse chunks
    'summary_use_mmr': True,
    # Use simple similarity search for specific questions
    'use_mmr': False,
    # MMR diversity factor (0 = max relevance, 1 = max diversity)
    'mmr_lambda': 0.5,
    # Minimum similarity score threshold
    'score_threshold': 0.0,
}

# Generator Model Configuration
GENERATOR_CONFIG = {
    'model_name': 'none',
    'use_generator': False,
}

# PDF Processing Configuration - Optimized for better context preservation
PDF_CONFIG = {
    'chunk_size': 800,  # characters per chunk (increased for better context)
    'chunk_overlap': 200,  # overlapping characters between chunks (increased for continuity)
    # Separators prioritize paragraph and sentence boundaries
    'separators': ["\n\n", "\n", ". ", "! ", "? ", "; ", ", ", " "],
}

# Flask Configuration
FLASK_CONFIG = {
    'host': '0.0.0.0',
    'port': 5000,
    'debug': True,
    'max_content_length': 16 * 1024 * 1024,  # 16MB
}
